# Generated by Django 5.1.7 on 2025-03-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmodel_options_alter_contactmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pavels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('descr', models.TextField(max_length=100, unique=True)),
            ],
        ),
    ]
