# Generated by Django 5.1.7 on 2025-03-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_pavels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pavels',
            name='descr',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
