# Generated by Django 5.1.7 on 2025-03-23 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_authormodel_booksmodel_delete_contactlinks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksmodel',
            name='author',
        ),
        migrations.DeleteModel(
            name='AuthorModel',
        ),
        migrations.DeleteModel(
            name='BooksModel',
        ),
    ]
