# Generated by Django 5.1.7 on 2025-03-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='website',
        ),
    ]
